- alias: "Input Number - Turn on fresh air fan"
  initial_state: true
  trigger:
    platform: state
    entity_id: input_number.fresh_air_minutes
  action:
    - service:
        timer.cancel
      data:
        entity_id: timer.fresh_air_timer
    - service:
        timer.start
      data_template:
        entity_id: timer.fresh_air_timer
        duration: 00:{{ trigger.to_state.state | int }}:00

- alias: "Input Time and Minute - Schedule fresh air fan"
  initial_state: true
  trigger:
    platform: time_pattern
    minutes: '/1'
  condition:
    condition: time
    after: '09:00:00'
    before: '22:00:00'
  action:
    service_template:
      # 4 time & duration settings for fresh air fan
      "
      {% set current_time = states('sensor.time') %}
      {% set start_time_1 = states.input_datetime.fresh_air_time_1.attributes.timestamp | int | timestamp_custom('%H:%M', False) %}
      {% set input_minute_1 = states.input_number.fresh_air_minutes_1.state | int %}
      {% set end_time_1 = (states.input_datetime.fresh_air_time_1.attributes.timestamp + input_minute_1 * 60) | int | timestamp_custom('%H:%M', False) %}
      {% set start_time_2 = states.input_datetime.fresh_air_time_2.attributes.timestamp | int | timestamp_custom('%H:%M', False) %}
      {% set input_minute_2 = states.input_number.fresh_air_minutes_2.state | int %}
      {% set end_time_2 = (states.input_datetime.fresh_air_time_2.attributes.timestamp + input_minute_2 * 60) | int | timestamp_custom('%H:%M', False) %}
      {% set start_time_3 = states.input_datetime.fresh_air_time_3.attributes.timestamp | int | timestamp_custom('%H:%M', False) %}
      {% set input_minute_3 = states.input_number.fresh_air_minutes_3.state | int %}
      {% set end_time_3 = (states.input_datetime.fresh_air_time_3.attributes.timestamp + input_minute_3 * 60) | int | timestamp_custom('%H:%M', False) %}
      {% set start_time_4 = states.input_datetime.fresh_air_time_4.attributes.timestamp | int | timestamp_custom('%H:%M', False) %}
      {% set input_minute_4 = states.input_number.fresh_air_minutes_4.state | int %}
      {% set end_time_4 = (states.input_datetime.fresh_air_time_4.attributes.timestamp + input_minute_4 * 60) | int | timestamp_custom('%H:%M', False) %}
      {% if (
          (input_minute_1 > 0 and
          current_time >= start_time_1 and
          current_time <= end_time_1) or
          (input_minute_2 > 0 and
          current_time >= start_time_2 and
          current_time <= end_time_2) or
          (input_minute_3 > 0 and
          current_time >= start_time_3 and
          current_time <= end_time_3) or
          (input_minute_4 > 0 and
          current_time >= start_time_4 and
          current_time <= end_time_4)
        )
      %}
      switch.turn_on
      {% else %}
      switch.turn_off
      {% endif %}
      "
    entity_id: switch.sonoff_10004f6d35
