homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret location_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret location_time_zone
  # Customization file
  customize: !include customize.yaml
  # Packages
  packages:
    # Google map navigation
    package_navigation: !include package_navigation.yaml
    # Fresh air fan schedule
    package_fresh_air_fan: !include package_fresh_air_fan.yaml
    # Routine notification
    package_routine_notification: !include package_routine_notification.yaml

# Enables the frontend
frontend:

# Hassio tab
hassio:

# Enables support for tracking state changes over time
recorder: !include recorder.yaml

# History
history:

# Logbook
logbook:

# Enables configuration UI
config:

# Custom updater for checking updates for custom components and cards
custom_updater:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  login_attempts_threshold: 5
  ip_ban_enabled: true

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Logger
logger:
  default: info

# Weather
weather:
  - platform: darksky
    api_key: !secret weather_api_key
    mode: hourly

# Nest Thermostat
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# MyQ garage door
cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain

# Mi jia sensors
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateways_key

# Ring Doorbell/Camera
ring:
  username: !secret ring_username
  password: !secret ring_password

# August door lock
august:
   login_method: phone
   username: !secret august_phonenumber
   password: !secret august_password

# Ring
camera:
  - platform: ring

binary_sensor:
  - platform: ring

sensor:
  - platform: ring

# Date time
sensor datetime:
  - platform: time_date
    display_options:
      - 'time'
      - 'date_time'

# Z-wave
zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_network_key

# Sonoff
sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  api_region: 'us'

# TV & box
media_player:
  - platform: samsungtv
    host: !secret samsungtv_host
    port: 8001
    mac: !secret samsungtv_mac
  - platform: xiaomi_tv

# Alexa Smart Home Integration
api:

alexa:
  smart_home:
    filter:
      include_entities:
        - light.ge_14294_inwall_smart_dimmer_level
        - lock.schlage_be469_touchscreen_deadbolt_locked
        - cover.garage
        - script.turn_off_bedroom_light
        - script.turn_on_bedroom_light_in_morning
        - script.unlock_garage_second_door
      include_domains:

# Scripts for Alexa
script: !include scripts.yaml

# IFTTT
ifttt:
  key: !secret ifttt_key
